# POST http://localhost:8000/api/signup
# Content-Type: application/json

# {
# "name" : "sumit",
# "email": "sumit@gmail.com",
# "password" : "123456"
# }

# POST http://localhost:8000/api/login
# Content-Type: application/json

# {
# "email": "sumit@gmail.com",
# "password" : "123456"
# }

# POST http://localhost:8000/api/logout
# Authorization: Bearer 4|szv7bXY7cl4KoUAp9lMK3SQhHGT8TK1HcMgd6AN9f55380e6

# __________________Post______________________


# GET http://localhost:8000/api/posts
# Authorization: Bearer 1|vDsdkpV9e9NwTkSVkTLj1E1NuRihsQ7Cn4YsN7LRd01ae349

# POST http://localhost:8000/api/posts
# Authorization: Bearer 1|vDsdkpV9e9NwTkSVkTLj1E1NuRihsQ7Cn4YsN7LRd01ae349
# Content-Type: multipart/form-data; boundary=boundary

# --boundary
# Content-Disposition: form-data; name="title"

# Post 1
# --boundary
# Content-Disposition: form-data; name="description"

# Here is the post 1
# --boundary
# Content-Disposition: form-data; name="image"; filename="vectjpeg.jpg"
# Content-Type: image/jpeg

# < C:/Users/ADMIN/Downloads/vectjpeg.jpg
# --boundary--





# GET http://localhost:8000/api/posts/1
# Authorization: Bearer 1|vDsdkpV9e9NwTkSVkTLj1E1NuRihsQ7Cn4YsN7LRd01ae349





@hostname =  http://localhost:8000/api/posts

POST {{hostname}}/1
Authorization: Bearer 1|vDsdkpV9e9NwTkSVkTLj1E1NuRihsQ7Cn4YsN7LRd01ae349
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Updated Post 1
--boundary
Content-Disposition: form-data; name="description"

Here is the post 1 Updated
--boundary
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpeg

< E:/SOFTWARE/1.jpg
--boundary
Content-Disposition: form-data; name="_method"

PUT
--boundary--

# curl -X POST http://localhost:8000/api/posts/1 \
#   -H "Authorization: Bearer Bearer 1|vDsdkpV9e9NwTkSVkTLj1E1NuRihsQ7Cn4YsN7LRd01ae349" \
#   -F "title=Updated Post 1" \
#   -F "description=Here is the post 1 Updated" \
#   -F "image=@E:/SOFTWARE/1.jpg" \
#   -F "_method=PUT"
